#
# Плагин поддерживает & цвета и HEX цвета.
# Пример применения "&" цветов: '&cДЕФИЦИТ'
# Пример применения HEX цветов: '&#FF5555ДЕФИЦИТ'
#

deficit_items: #Предметы для которых будет дефицит (их можно создавать бесконечно)
  item1: #Предмет 1
    material: diamond #Материал предмета
    limit: 8000 #Лимит после которого дефицит для предмета включится
    limit_end: #Что будет при попытке вскопать алмазную руду или подобрать алмаз
      VirtualEntity: #Появляться эффекты из VirtualEntityAPI
        enable: true #Включено или выключен
        types: #Типы
          - explosion #Взрыв
          - lightning #Молния
          - ParticleAnimation1 #Анимация 1 состоящая из партиклов (придумай анимацию сам)
          - ParticleAnimation2 #Анимация 2 состоящая из партиклов (придумай анимацию сам)
      Title: #Появляться Title и SubTitle
        enable: true #Включено или выключен
        title: '&cДЕФИЦИТ' #Текст для Title
        subtitle: '&cНа этот предмет закончился лимит' #Текст для SubTitle
      BossBar:
        enable: false #Включено или выключен
        bossbar: '&cНа этот предмет закончился лимит!' #Текст для BossBar
        type: SEGMENTED_10 #Тип BossBar
        color: RED #Цвет BossBar
        time: 5 #Длительность BossBar
      Message: #Сообщение в чат для игрока
        enable: true #Включено или выключен
        message: #Сообщение (можно в несколько строк)
          - '&cДЕФИЦИТ &b>> &cЭтот предмет невозможно добыть из-за его дефицита!'