name: SeeResourcesDeficit
version: '${project.version}'
main: ru.gdev.seeresourcesdeficit.SeeResourcesDeficit
api-version: '1.16'
load: STARTUP
depend: [VirtualEntityAPI]
authors: [GDev]
website: https://seemine.su
commands:
  seeresourcesdeficit:
    usage: /seeresourcesdeficit reload|enable|disable
    permission: seeresourcesdeficit.admin
    permission-message: '&#FF5555У вас нету прав!'
    aliases: [seerd]
permissions:
  seeresourcesdeficit.admin:
    default: op
